# nama Konfigurasi 
name: run Tests

# branch github
on: 
    push: 
        branches: 
            - main

# tugas yang di lakukan
jobs:
    # test
    test:
        # test di server ubuntu
        runs-on: ubuntu-latest

        # langkah
        steps:
            # sub judul perlangkah
            - name: Checkout code
              uses: actions/checkout@v3

              # setup python dengan versi yang sesuai
            - name: Set Up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.11'
                
            # lokasi file pastikan sesuai
            - name: Install dependencies
              run: pip install -r requirements.txt
            
              # lokasi file yang sesuai
            - name: Run test
              run: pytest test-app.py
